/* GENERATED by scripts/gen-service-worker.cjs — do not hand-edit the
   PRECACHE_URLS list, re-run the script instead (source: content.js
   phonemeIds + the core file set hardcoded in the generator).
   §2 offline-first / §17.1 test 7: the whole app must work with no network. */
const CACHE_NAME = 'bloom-academy-v3';
const PRECACHE_URLS = [
  "./",
  "app.html",
  "content.js",
  "audio-manager.jsx",
  "styles.css",
  "manifest.webmanifest",
  "vendor/react.development.js",
  "vendor/react-dom.development.js",
  "vendor/babel.min.js",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/fonts/fredoka-variable.woff2",
  "assets/fonts/nunito-variable.woff2",
  "assets/phonemes/a.wav",
  "assets/phonemes/b.wav",
  "assets/phonemes/c.wav",
  "assets/phonemes/d.wav",
  "assets/phonemes/e.wav",
  "assets/phonemes/f.wav",
  "assets/phonemes/g.wav",
  "assets/phonemes/h.wav",
  "assets/phonemes/i.wav",
  "assets/phonemes/j.wav",
  "assets/phonemes/k.wav",
  "assets/phonemes/l.wav",
  "assets/phonemes/m.wav",
  "assets/phonemes/n.wav",
  "assets/phonemes/o.wav",
  "assets/phonemes/p.wav",
  "assets/phonemes/q.wav",
  "assets/phonemes/r.wav",
  "assets/phonemes/s.wav",
  "assets/phonemes/t.wav",
  "assets/phonemes/u.wav",
  "assets/phonemes/v.wav",
  "assets/phonemes/w.wav",
  "assets/phonemes/x.wav",
  "assets/phonemes/y.wav",
  "assets/phonemes/z.wav",
  "assets/phonemes/sh.wav",
  "assets/phonemes/ch.wav",
  "assets/phonemes/th.wav",
  "assets/phonemes/wh.wav",
  "assets/phonemes/ng.wav",
  "assets/phonemes/ee.wav",
  "assets/phonemes/oo.wav"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

// Cache-first: the game must work with networking disabled (§17.1 test 7).
// Falls back to network for anything not precached, and silently ignores
// fetch failures rather than surfacing an error to the child (§22.2).
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }
        return res;
      }).catch(() => cached);
    })
  );
});
